# Do you want health to be separated across worlds
health: false

# Do you want to allow this plugin to control which worlds are creative/survival
worldTypes: true

# Players you wish to never switch inventories
# Separated by a comma ,
ignore: Pluckerpluck, randomStranger