name: MultiInv
main: uk.co.tggl.pluckerpluck.multiinv.MultiInv
version: 2.3.2
website: http://www.tggl.co.uk
author: Pluckerpluck
description: >
             This is a plugin to create seperate inventories for each world
commands:
  multiinv:
    description: Saves and loads inventory
    usage: |
           /<command> save- saves inventory
           /<command> load - loads inventory
           /<command> debug - starts debugging