name: MultiInv
main: uk.co.tggl.pluckerpluck.multiinv.MultiInv
version: 3.0.0
website: http://www.tggl.co.uk
author: Pluckerpluck
description: >
             This is a plugin to create seperate inventories for each world


commands:
  multiinv:
    description: MultiInv admin commands
    usage: |
           /<command> delete <player> - delete all inventories for player (doesn't work)